[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.4.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.2.0"

[[constraint]]
  name = "github.com/cloudfoundry-community/go-uaa"
  branch = "autoapprove-bool"
  source = "https://github.com/drnic/go-uaa.git"
